### ISSUE TITLE
cannot reproduce correct result

### ISSUE THREAD

**Issue by yuzhi535** [edward3862/Analogist#4]
Hi @edward3862
Thanks for your great work! I'm reproducing the result and find that the model could not reconstruct the face well. what the hyper parameters about this image in the demo website? 
<img width="945" alt="Screenshot 2024-10-07 at 12 01 38" src="https://github.com/user-attachments/assets/97653c98-f7dd-43df-a8b7-db8e80201013">

**Comment by edward3862** [comment]
Hi @yuzhi535 , I used the following script, basically no major parameters changes:

```
python analogist.py \
    --input_grid example/normal_processed/001/input.png \
    --prompt_file example/normal_processed/001/prompts.txt \
    --output_dir results/example/normal_processed/001 \
    --num_images_per_prompt 1 --res 1024 \
    --sac_start_layer 3 --sac_end_layer 11 \
    --cam_start_layer 3 --cam_end_layer 11 \
    --strength 0.98 --scale_sac 1.3 --guidance_scale 15
```

I guess the poor result is due to the screenshots. Here is the raw image file that I used: [normal_processed.zip](https://github.com/user-attachments/files/17373354/normal_processed.zip)

Here is what I got:
![image](https://github.com/user-attachments/assets/5a16132e-1028-4193-8618-0ef90830540b)
